apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tbctrl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tbctrl
subjects:
  - kind: ServiceAccount
    name: tbctrl
    namespace: default
