apiVersion: v1
kind: Service
metadata:
  name: tbctrl
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: tbctrl
    app.kubernetes.io/instance: tbctrl
