apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tbctrl.fullname" . }}-rolebinding
  labels:
    {{- include "tbctrl.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tbctrl.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "tbctrl.fullname" . }}-controller
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tbctrl.fullname" . }}-leader-election-rolebinding
  labels:
    {{- include "tbctrl.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "tbctrl.fullname" . }}-leader-election-role
subjects:
  - kind: ServiceAccount
    name: {{ include "tbctrl.fullname" . }}-controller
    namespace: system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tbctrl.fullname" . }}-proxy-rolebinding
  labels:
    {{- include "tbctrl.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tbctrl.fullname" . }}-proxy-role
subjects:
  - kind: ServiceAccount
    name: {{ include "tbctrl.fullname" . }}-controller
    namespace: system
