{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tbctrl.fullname" . }}-metrics-service
  labels:
    {{- include "tbctrl.labels" . | nindent 4 }}
  annotations:
    prometheus.io/port: '{{ .Values.metrics.port }}'
    prometheus.io/scrape: 'true'
  {{- with .Values.metrics.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.serviceType }}
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    {{- include "tbctrl.selectorLabels" . | nindent 4 }}
{{- end }}