{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tbctrl.fullname" . }}
  labels:
    {{- include "tbctrl.labels" . | nindent 4 }}
  annotations:
    prometheus.io/port: '{{ .Values.metrics.port }}'
    prometheus.io/scrape: 'true'
  {{- with .Values.metrics.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.serviceType }}
  ports:
    - port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "tbctrl.selectorLabels" . | nindent 4 }}
{{- end }}