apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  namespace: system
  labels:
    app.kubernetes.io/name: tbctrl
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/name: tbctrl
