# Default values for tbctrl.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

debug:
  logLevel: 0

image:
  repository: ghcr.io/zoomoid/tbctrl
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  # tag: "latest"

metrics:
  enabled: true
  serviceType: ClusterIP
  port: 8443
  serviceMonitor: false

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations:
  kubectl.kubernetes.io/default-container: controller

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - "ALL"
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

resources:
  requests:
    memory: "64Mi"
    cpu: "100m"
  limits:
    memory: "128Mi"
    cpu: "500m"

nodeSelector: {}

tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Equal
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Equal
  - effect: NoSchedule
    value: "true"
    key: "node.cloudprovider.kubernetes.io/uninitialized"
  - effect: NoSchedule
    operator: Exists
    key: "node.kubernetes.io/not-ready"

dnsPolicy: ""

affinity: {}
