name: "Publish release"

on: 
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  publish-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install google/ko
        uses: imjasonh/setup-ko@v0.6

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push image
        run: |
          export VERSION=${{ github.ref_name }}
          export BUILD=${{ github.sha }}
          ko publish ./ --platform=linux/amd64 -B --tags=${{ github.ref_name }}  --sbom=none
          ko publish ./ --platform=linux/amd64 -B --sbom=none
  publish-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}